In [2]:
import numpy as np
import pandas as pd
from sklearn import metrics

df=pd.read_csv(r"E:/ML-LAB-main/Play Tennis.csv")
value=['Outlook','Temprature','Humidity','Wind']
df

len(df)

df.shape

df.head()

df.tail()

df.describe()

from sklearn import preprocessing
string_to_int= preprocessing.LabelEncoder()                    
df=df.apply(string_to_int.fit_transform) 
df

feature_cols = ['Outlook','Temprature','Humidity','Wind']
X = df[feature_cols ]                               
y = df.Play_Tennis

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

from sklearn.tree import DecisionTreeClassifier                             
classifier =DecisionTreeClassifier(criterion="gini", random_state=100)     
classifier.fit(X_train, y_train)

y_pred= classifier.predict(X_test) 

from sklearn.metrics import accuracy_score
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

data_p=pd.DataFrame({'Actual':y_test, 'Predicted':y_pred})  
data_p

from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))

Accuracy: 0.8
[[0 1]
 [0 4]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.80      1.00      0.89         4

    accuracy                           0.80         5
   macro avg       0.40      0.50      0.44         5
weighted avg       0.64      0.80      0.71         5



C:\Users\derri\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\derri\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\derri\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


In [3]:
import numpy as np
import pandas as pd
from sklearn import metrics

df=pd.read_csv(r"E:/ML-LAB-main/Play Tennis.csv")
value=['Outlook','Temprature','Humidity','Wind']
df

len(df)

df.shape

df.head()

df.tail()

df.describe()

from sklearn import preprocessing
string_to_int= preprocessing.LabelEncoder()                    
df=df.apply(string_to_int.fit_transform) 
df

feature_cols = ['Outlook','Temprature','Humidity','Wind']
X = df[feature_cols ]                               
y = df.Play_Tennis

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

from sklearn.tree import DecisionTreeClassifier                             
classifier =DecisionTreeClassifier(criterion="gini", random_state=100)     
classifier.fit(X_train, y_train)

y_pred= classifier.predict(X_test) 

from sklearn.metrics import accuracy_score
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

data_p=pd.DataFrame({'Actual':y_test, 'Predicted':y_pred})  
data_p

from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))

Accuracy: 0.8
[[2 0]
 [1 2]]
              precision    recall  f1-score   support

           0       0.67      1.00      0.80         2
           1       1.00      0.67      0.80         3

    accuracy                           0.80         5
   macro avg       0.83      0.83      0.80         5
weighted avg       0.87      0.80      0.80         5



In [4]:
import numpy as np
import pandas as pd
from sklearn import metrics

df=pd.read_csv(r"E:/ML-LAB-main/Play Tennis.csv")
value=['Outlook','Temprature','Humidity','Wind']
df

len(df)

df.shape

df.head()

df.tail()

df.describe()

from sklearn import preprocessing
string_to_int= preprocessing.LabelEncoder()                    
df=df.apply(string_to_int.fit_transform) 
df

feature_cols = ['Outlook','Temprature','Humidity','Wind']
X = df[feature_cols ]                               
y = df.Play_Tennis

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

from sklearn.tree import DecisionTreeClassifier                             
classifier =DecisionTreeClassifier(criterion="gini", random_state=100)     
classifier.fit(X_train, y_train)

y_pred= classifier.predict(X_test) 

from sklearn.metrics import accuracy_score
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

data_p=pd.DataFrame({'Actual':y_test, 'Predicted':y_pred})  
data_p

from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))

Accuracy: 0.4
[[0 0]
 [3 2]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.40      0.57         5

    accuracy                           0.40         5
   macro avg       0.50      0.20      0.29         5
weighted avg       1.00      0.40      0.57         5



C:\Users\derri\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\derri\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\derri\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


In [5]:
import numpy as np
import pandas as pd
from sklearn import metrics

df=pd.read_csv(r"E:/ML-LAB-main/Play Tennis.csv")
value=['Outlook','Temprature','Humidity','Wind']
df

len(df)

df.shape

df.head()

df.tail()

df.describe()

from sklearn import preprocessing
string_to_int= preprocessing.LabelEncoder()                    
df=df.apply(string_to_int.fit_transform) 
df

feature_cols = ['Outlook','Temprature','Humidity','Wind']
X = df[feature_cols ]                               
y = df.Play_Tennis

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

from sklearn.tree import DecisionTreeClassifier                             
classifier =DecisionTreeClassifier(criterion="gini", random_state=100)     
classifier.fit(X_train, y_train)

y_pred= classifier.predict(X_test) 

from sklearn.metrics import accuracy_score
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

data_p=pd.DataFrame({'Actual':y_test, 'Predicted':y_pred})  
data_p

from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))

Accuracy: 0.8
[[1 0]
 [1 3]]
              precision    recall  f1-score   support

           0       0.50      1.00      0.67         1
           1       1.00      0.75      0.86         4

    accuracy                           0.80         5
   macro avg       0.75      0.88      0.76         5
weighted avg       0.90      0.80      0.82         5

